Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using proje.Models;

namespace proje.Controllers
{
    using Models;
    using proje.App_Classes;
    using System.Drawing;
    public class adminController : Controller
    {
        uzayblgContext context = new uzayblgContext();

        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult yazaronaylari()
        {
            var data = context.kullanicis.Where(x => x.yazar == true && x.onaylandi == false).ToList();
            return View(data);
        }
        //public ActionResult girisyap()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult girisyap(admin admn)
        //{
        //    string ka = validateuser(admn.admin_ka, admn.admin_sf);
        //    if (!string.IsNullOrEmpty(ka))//rol null ya da boş değilise demektir
        //    { //formsauthenticationticket oturumun ne zaman açılacağını ne zaman düşeceği gibi bilgileri tutar
        //        FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, admn.admin_ka, DateTime.Now, DateTime.Now.AddMinutes(15), true, ka, FormsAuthentication.FormsCookiePath);//tutulucak cookieyi al
        //        HttpCookie ck = new HttpCookie(FormsAuthentication.FormsCookieName);//kendi cookie namesini çek

        //        if (ticket.IsPersistent)//kalıcı ise
        //        {
        //            ck.Expires = ticket.Expiration;//ck nin bitiş süresi ticketin süresine eşit olsun
        //        }

        //        Response.Cookies.Add(ck);
        //        FormsAuthentication.RedirectFromLoginPage(admn.admin_ka, true);

        //    }
        //    return RedirectToAction("makaleekle");//tekrar giriş yapa gidicek
        //}
        //string validateuser(string ka, string pwd)
        //{
        //    //firsordefaultta yoksa null döndürür hata vermez
        //    admin admn = context.admins.FirstOrDefault(x => x.admin_ka == ka && x.admin_sf == pwd);
        //    if (admn != null)
        //    {
        //        return  admn.admin_ka; //roladini döndürür
        //    }
        //    else
        //    {
        //        return "";


        //    }
        //}
        public ActionResult onayver(int kul_id)
        {
            kullanici kl = context.kullanicis.FirstOrDefault(x => x.kullanici_id == kul_id);
            kl.onaylandi = true;

            context.SaveChanges();
            return RedirectToAction("yazaronaylari");
        }

        public ActionResult kategoriekle(string p)
        {
            var degerler = from d in context.kategoris select d;//degerleri rols tablosundan çekip dyle aldık
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.kategori_adi.Contains(p));
            }
            return View(degerler.ToList());
        }
        [HttpGet]
        public ActionResult yenikategori()
        {
            return View();
        }
        [HttpPost]//sayfaya post işlemi oldupunda butona basıldığında falan
        public ActionResult yenikategori(kategori kategori)
        {
            context.kategoris.Add(kategori);
            context.SaveChanges();
            return RedirectToAction("kategoriekle");
        }
        public ActionResult sil(int id)
        {
            var kategori = context.kategoris.Find(id);
            context.kategoris.Remove(kategori);
            context.SaveChanges();
            return RedirectToAction("kategoriekle");
        }
        public ActionResult güncelle(int id)
        {
            var ktgr = context.kategoris.Find(id);
            return View("güncelle", ktgr);
        }
        public ActionResult gunyap(kategori kt)
        {
            var kategori = context.kategoris.Find(kt.kategori_id);
            kategori.kategori_adi = kt.kategori_adi;
            kategori.kategori_aciklama = kt.kategori_aciklama;
            context.SaveChanges();
            return RedirectToAction("kategoriekle");
        }
        public ActionResult makaleekle(string p)
        {
            var degerler = from d in context.makales select d;//degerleri rols tablosundan çekip dyle aldık
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.makale_baslik.Contains(p));
            }
            return View(degerler.ToList());
        }

        public ActionResult etiketekle(string p)
        {

            var degerler = from d in context.etikets select d;//degerleri rols tablosundan çekip dyle aldık
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.etiket_adi.Contains(p));
            }
            return View(degerler.ToList());
        }
        public ActionResult rolekle(string p)
        {
            var degerler = from d in context.rols select d;//degerleri rols tablosundan çekip dyle aldık
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.rol_adi.Contains(p));
            }
            return View(degerler.ToList());
            //var degerler = context.rols.ToList();
            //return View(degerler);


        }
        public ActionResult adminekle(string p)
        {
            var degerler = from d in context.admins select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.admin_ka.Contains(p));
            }
            return View(degerler.ToList());
        }
        public ActionResult kullaniciekle(string p)
        {
            var degerler = from d in context.kullanicis select d;//degerleri rols tablosundan çekip dyle aldık
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.kullanici_adi.Contains(p));
            }
            return View(degerler.ToList());
            /*var degerler = context.kullanicis.ToList();
            return View(degerler);*/
        }
        [HttpGet]
        public ActionResult yenietiket()
        {

            return View();
        }
        [HttpPost]
        public ActionResult yenietiket(etiket etiket)
        {
            context.etikets.Add(etiket);
            context.SaveChanges();
            return RedirectToAction("etiketekle");
        }
        [HttpGet]
        public ActionResult yenikullanici()
        {
            return View();
        }
        [HttpPost]
        public ActionResult yenikullanici(kullanici kull, string rbkadin, string rberkek)
        {
            if (!string.IsNullOrEmpty(rberkek))
            {
                kull.kullanici_cinsiyet = true;
            }
            if (!string.IsNullOrEmpty(rbkadin))
            {
                kull.kullanici_cinsiyet = false;
            }
            kull.yazar = false;
            kull.onaylandi = true;
            kull.aktif = true;
            kull.kullanici_dogum = kull.kullanici_dogum;
            kull.kullaniciadi = kull.kullaniciadi;
            kull.sifre = kull.sifre;
            kull.kullanici_kayit = DateTime.Now;
            context.kullanicis.Add(kull);
            context.SaveChanges();
            return RedirectToAction("kullaniciekle");
            /*
            context.kullanicis.Add(kull);
            context.SaveChanges();
            return RedirectToAction("kullaniciekle");*/
        }
        [HttpGet]
        public ActionResult yenimakale()
        {
            ViewBag.kategoriler = context.kategoris.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult yenimakale(makale mkl , HttpPostedFileBase rsm)

        {
            
            Image img = Image.FromStream(rsm.InputStream);
            Bitmap kucuk = new Bitmap(img, settings.resimkucukboyut);
            Bitmap buyuk = new Bitmap(img, settings.resimbuyukboyut);
            Bitmap orta = new Bitmap(img, settings.resimortaboyut);
            kucuk.Save(Server.MapPath("/Content/Makaleresim/kucuk/"+rsm.FileName));
            buyuk.Save(Server.MapPath("/Content/Makaleresim/buyuk/" + rsm.FileName));
            orta.Save(Server.MapPath("/Content/Makaleresim/orta/" + rsm.FileName));

            resim resm = new resim();
            resm.buyukboyut = "/Content/Makaleresim/buyuk/" + rsm.FileName;
            resm.ortaboyut = "/Content/Makaleresim/orta/" + rsm.FileName;
           resm.kucukboyut= "/Content/Makaleresim/kucuk/" + rsm.FileName;
           context.resims.Add(resm);
           context.SaveChanges();
           return View();
        
        
        }

private void alert(char p)
{
 	throw new NotImplementedException();
}

        [HttpGet]
        public ActionResult yenirol()
        {

            return View();
        }
        [HttpPost]
        public ActionResult yenirol(rol rolss)
        {
            context.rols.Add(rolss);
            context.SaveChanges();
            return RedirectToAction("rolekle");
        }
        [HttpGet]
        public ActionResult yeniadmin()
        {

            return View();
        }
        [HttpPost]
        public ActionResult yeniadmin(admin admin)
        {
            context.admins.Add(admin);
            context.SaveChanges();
            return RedirectToAction("adminekle");
        }

        public ActionResult etiketsil(int id)
        {
            var etiket = context.etikets.Find(id);
            context.etikets.Remove(etiket);
            context.SaveChanges();
            return RedirectToAction("etiketekle");
        }
        public ActionResult kullanicisil(int id)
        {

Views/admin/adminekle.cshtml
@{
    ViewBag.Title = "adminekle";
    Layout = "~/Views/Shared/admin.cshtml";
}

@using (Html.BeginForm("adminekle", "admin", FormMethod.Get))
{
    <p>ARANACAK ADMİN ADI:@Html.TextBox("p")
        <input type="submit" value="ARA"/>
    </p>
    
}
@model IEnumerable<proje.Models.admin>
<table class="table table-bordered">
    <tr>
        <th>ADMİN ID</th>
        <th>ADMİN KULLANICI ADI</th>
        <th>ADMİN SİFRE</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        
        
    </tr>
    <tbody>
         @foreach (proje.Models.admin admn in Model)
         {
             <tr>
                 <th>@admn.admin_id</th>
                 <td>@admn.admin_ka</td>
                 <td>@admn.admin_sf</td>
                 <td><a href="/admin/adminsil/@admn.admin_id" class="btn btn-warning">SİL</a></td>
                 <td><a href="/admin/adminguncelle/@admn.admin_id" class="btn btn-primary">GÜNCELLE</a></td>
                
             </tr>
         }
    </tbody>
</table>
@*<a href ="yeniadmin" class="btn btn-danger">YENİ ADMİN EKLE</a>*@
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Admin Ekle
</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">ADMİN EKLEME EKRANI</h2>

            </div>
            <form method="post" action="yeniadmin">
                <div class="modal-body">
                   
                    <br />
            <label>ADMİN KULLANICI ADI</label>
        <input type="text" class="form-control" name="admin_ka" />
                    <br />
        <label>ADMİN ŞİFRE</label>
        <input type="text" class="form-control" name="admin_sf" />
                    <br />
    
        <button class="btn btn-danger">ADMİN EKLE</button>
    </div>
        </form>
        </div>

    </div>
</div>


Views/admin/adminguncelle.cshtml
@{
    ViewBag.Title = "adminguncelle";
    Layout = "~/Views/Shared/ViewPage2.cshtml";
}

<h2>ADMİN   GÜNCELLE</h2>
@model proje.Models.admin
@using (Html.BeginForm("admingun", "admin", FormMethod.Post))
{
     <div class="form-group">
         <br />
           @Html.LabelFor(m=>m.admin_id)
        @Html.TextBoxFor(m=>m.admin_id , new { @class="form-control"})
         <br />
        @Html.LabelFor(m=>m.admin_ka)
        @Html.TextBoxFor(m=>m.admin_ka , new { @class="form-control"})
       <br />
       <br />
        @Html.LabelFor(m=>m.admin_sf)
        @Html.TextBoxFor(m=>m.admin_sf , new { @class="form-control"})
        <br />
         <div >
    <button class="btn btn-primary">ADMİN GÜNCELLE</button>
</div>
         </div>}

Views/admin/etiketekle.cshtml
@{
    ViewBag.Title = "ETİKETLER";
    Layout = "~/Views/Shared/admin.cshtml";
}

@using (Html.BeginForm("etiketekle", "admin", FormMethod.Get))
{
    <p>ARANACAK ROL ADI:@Html.TextBox("p")
        <input type="submit" value="ARA"/>
    </p>
    
}
@model IEnumerable<proje.Models.etiket>
<table class="table table-bordered">
    <tr>
        <th>ETİKET ID</th>
        <th>ETİKET ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        
        
    </tr>
    <tbody>
         @foreach (proje.Models.etiket etkt in Model)
         {
             <tr>
                 <th>@etkt.etiket_id</th>
                 <td>@etkt.etiket_adi</td>
                 <td><a href="/admin/etiketsil/@etkt.etiket_id" class="btn btn-danger">SİL</a></td>
                 <td><a href="/admin/etiketguncelle/@etkt.etiket_id" class="btn btn-info">GÜNCELLE</a></td>

             </tr>
         }
    </tbody>
</table>
<a href ="yenietiket" class="btn btn-danger">YENİ ETİKET EKLE</a>

Views/admin/girisyap.cshtml
@{
    ViewBag.Title = "GİRİŞ YAP";
    Layout = "~/Views/Shared/ViewPage1.cshtml";
}

   <form action="/admin/girisyap" method="post" class="login100-form validate-form p-b-33 p-t-5">

					<div class="wrap-input100 validate-input" data-validate = "Kullanıcı Adını Giriniz:">
						<input class="input100" type="text" name="admin_ka" placeholder="Kullanıcı Adını Giriniz:">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Şifreyi Giriniz:">
						<input class="input100" type="password" name="admin_sf" placeholder="Şifreyi Giriniz:">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						 <input type="submit" name="name" value="GİRİŞ YAP" />
					</div>
       </form>

Views/admin/güncelle.cshtml
@{
    ViewBag.Title = "güncelle";
    Layout = "~/Views/Shared/ViewPage2.cshtml";
}

@model proje.Models.kategori

@using (Html.BeginForm("gunyap","admin",FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m=>m.kategori_id)
        @Html.TextBoxFor(m=>m.kategori_id , new { @class="form-control"})
      <br />
        @Html.LabelFor(m=>m.kategori_adi)
        @Html.TextBoxFor(m=>m.kategori_adi , new { @class="form-control"})
        <br />
        @Html.LabelFor(m=>m.kategori_aciklama)
        @Html.TextBoxFor(m=>m.kategori_aciklama , new { @class="form-control"})

    </div>
<div >
    <button class="btn btn-primary">KATEGORİ GÜNCELLE</button>
</div>

}

Views/admin/kategoriekle.cshtml
@{
    ViewBag.Title = "KATEGORİ ";
    Layout = "~/Views/Shared/admin.cshtml";
}
@using (Html.BeginForm("kategoriekle", "admin", FormMethod.Get))
{
    <p>ARANACAK KATEGORİ ADI:@Html.TextBox("p")
        <input type="submit" value="ARA"/>
    </p>
    
}
@model IEnumerable<proje.Models.kategori>
<table class="table table-bordered">
    <tr>
        <th>KATEGORİ ID </th>
        <th>KATEGORİ ADI</th>
        <th>KATEGORİ AÇIKLAMA</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    <tbody>
        @foreach(proje.Models.kategori kategori in Model)
        {
            <tr>
            <td>@kategori.kategori_id</td>
            <td>@kategori.kategori_adi</td>
            <td>@kategori.kategori_aciklama</td>
            <td><a href="/admin/sil/@kategori.kategori_id" class="btn btn-warning">SİL</a></td>
            <td><a href="/admin/güncelle/@kategori.kategori_id" class="btn btn-success">GÜNCELLE</a></td>


                </tr>
        }
    </tbody>
</table>
@*<a href ="yenikategori" class="btn btn-danger">YENİ KATEGORİ EKLE</a>*@
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Kategori Ekle
</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">KATEGORİ EKLEME EKRANI</h2>

            </div>
            <form method="post" action="yenikategori">
                <div class="modal-body">
                   
                    <br />
            <label>KATEGORİ ADI</label>
        <input type="text" class="form-control" name="kategori_adi" />
                    <br />
        <label>KATEGORİ TANIMI</label>
        <input type="text" class="form-control" name="kategori_aciklama" />
                    <br />
    
        <button class="btn btn-danger">KATEGORİ EKLE</button>
    </div>
        </form>
        </div>

    </div>
</div>


Views/admin/kullaniciekle.cshtml
@{
    ViewBag.Title = "KULLANICILAR";
    Layout = "~/Views/Shared/admin.cshtml";
}

@using (Html.BeginForm("kullaniciekle","admin",FormMethod.Get))
{
 <p>ARANACAK KULLANICI ADI:@Html.TextBox("p")
        <input type="submit" value="ARA"/>
    </p>
    
}
@model IEnumerable<proje.Models.kullanici>

<table class="table table-bordered">
    <tr>
        <th>KULLANICI ID</th>
        <th>KULLANICI ADI</th>
        <th>KULLANICI ŞİFRE</th>
        <th>KULLANICI K.A.</th>
        <th>KULLANICI MAİL</th>
        <th>KULLANICI CİNSİYET</th>
        <th>KULLANICI DOĞUM TARİHİ</th>
        <th>KULLANICI KAYIT TARİHİ</th>
        <th>KULLANICI RESİMID</th>
        <th>KULLANICI YAZAR</th>
        <th>KULLANICI ONAYLANDI</th>
        <th>KULLANICI AKTİF</th>
        <th>KULLANICI AÇIKLAMA</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        
    </tr>
    <tbody>
         @foreach (proje.Models.kullanici klnc in Model)
         {
             <tr>
                 <th>@klnc.kullanici_id</th>
                 <td>@klnc.kullanici_adi</td>
                 <td>@klnc.sifre</td>
                 <td>@klnc.kullaniciadi</td>
                 <td>@klnc.kullanici_mail</td>
                 <td>@klnc.kullanici_cinsiyet</td>
                 <td>@klnc.kullanici_dogum</td>
                 <td>@klnc.kullanici_kayit</td>
                 <td>@klnc.kullanici_resimid></td>
                 <td>@klnc.yazar</td>
                 <td>@klnc.onaylandi</td>
                 <td>@klnc.aktif</td>
                 <td>@klnc.aciklama</td>
                  <td><a href="/admin/kullanicisil/@klnc.kullanici_id" class="btn btn-warning">SİL</a></td>
                 <td><a href="/admin/kullaniciguncelle/@klnc.kullanici_id" class="btn btn-primary">GÜNCELLE</a></td>
                 </tr>
         }
    </tbody>
</table>
@*<a href ="yenikullanici" class="btn btn-danger">YENİ KULLANICI EKLE</a>*@
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Kullanıcı Ekle
</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">KULLANICI EKLEME EKRANI</h2>

            </div>
            <form method="post" action="yenikullanici">
                <div class="modal-body">
                   
                    <br />
          <label>KULLANICI ADI-SOYADI</label>
        <input type="text" class="form-control" name="kullanici_adi" />
                    <br />
         <label>KULLANICI ŞİFRE</label>
        <input type="text" class="form-control" name="sifre" />
                    <br />
                       <label>KULLANICI ADI</label>
        <input type="text" class="form-control" name="kullaniciadi" />
         <label>KULLANICI MAİL</label>
        <input type="text" class="form-control" name="kullanici_mail" />
    <br />
                     <label>CİNSİYET</label> 
        
                  <input type="radio" name="rbkadin" value="KADIN " /> <span>KADIN</span>
                   <input type="radio" name="rberkek" value="ERKEK " /> <span>ERKEK</span>
    <br />
                    <label>KULLANICI DOGUM TARİHİ</label>
        <input type="date" class="form-control" name="kullanici_dogum" />
                    <br />
        <button class="btn btn-danger">kULLANICI  EKLE</button>
    </div>
        </form>
        </div>

    </div>
</div>

Views/admin/kullaniciguncelle.cshtml
@{
    ViewBag.Title = "kullaniciguncelle";
    Layout = "~/Views/Shared/ViewPage2.cshtml";
}

<h2>KULLANICI GÜNCELLE</h2>
@model proje.Models.kullanici
@using (Html.BeginForm("kulgun", "admin", FormMethod.Post))
{
    <div class="form-group">
        <br />
       @Html.LabelFor(m=>m.kullanici_id)
        @Html.TextBoxFor(m=>m.kullanici_id , new { @class="form-control"})
        <br />
       @Html.LabelFor(m=>m.kullanici_adi)
        @Html.TextBoxFor(m=>m.kullanici_adi , new { @class="form-control"})
         <br />
       @Html.LabelFor(m=>m.sifre)
        @Html.TextBoxFor(m=>m.sifre , new { @class="form-control"})
         <br />
       @Html.LabelFor(m=>m.kullaniciadi)
        @Html.TextBoxFor(m=>m.kullaniciadi , new { @class="form-control"})
        <br />
       @Html.LabelFor(m=>m.kullanici_mail)
        @Html.TextBoxFor(m=>m.kullanici_mail , new { @class="form-control"})
           <br />
       @Html.LabelFor(m=>m.kullanici_cinsiyet)
        @Html.RadioButtonFor(m=>m.kullanici_cinsiyet , new { @class="form-control"})
          @Html.RadioButtonFor(m=>m.kullanici_cinsiyet , new { @class="form-control"})
         <br />
       @Html.LabelFor(m=>m.kullanici_dogum)
        @Html.TextBoxFor(m=>m.kullanici_dogum , new { @class="form-control"})
           <br />
 
           </div>
     <div >
    <button class="btn btn-primary">KULLANICI GÜNCELLE</button>
</div>
}
    

Views/admin/makaleekle.cshtml
@{
    ViewBag.Title = "MAKALELER";
    Layout = "~/Views/Shared/admin.cshtml";
}
@using (Html.BeginForm("makaleekle", "admin", FormMethod.Get))
{
    <p>ARANACAK MAKALE BAŞLIĞI:@Html.TextBox("p")
        <input type="submit" value="ARA"/>
    </p>
    
}
@model IEnumerable<proje.Models.makale>
<table class="table table-bordered">
    <tr>
        <th>MAKALE ID</th>
        <th>MAKALE BAŞLIĞI</th>
        <th>MAKALE İÇERİK</th>
        <th>MAKALE TARİH</th>
        <th>MAKALE KATEGORİ</th>
        <th>MAKALE GÖRÜNTÜLENME</th>
        <th>MAKALE BEGENİ</th>
        <th>MAKALE YAZARID</th>
        <th>MAKALE RESİMID</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        
    </tr>
    <tbody>
         @foreach (proje.Models.makale mkl in Model)
         {
             <tr>
                 <th>@mkl.makale_id</th>
                 <td>@mkl.makale_baslik</td>
                 <td>@mkl.makale_icerik</td>
                 <td>@mkl.makale_tarih</td>
                 <td>@mkl.makale_kategorid</td>
                 <td>@mkl.makale_goruntulenme</td>
                 <td>@mkl.makale_begeni</td>
                 <td>@mkl.makale_yazarid</td>
                 <td>@mkl.resim_id></td>
                 <td><a href="/admin/makalesil/@mkl.makale_id" class="btn btn-warning">SİL</a></td>
                 <td><a href="/admin/makaleguncelle/@mkl.makale_id" class="btn btn-primary">GÜNCELLE</a></td>
             </tr>
         }
    </tbody>
</table>
<a href ="yenimakale/" class="btn btn-danger">YENİ MAKALE EKLE</a>

Views/admin/rolekle.cshtml
@{
    ViewBag.Title = "rolekle";
    Layout = "~/Views/Shared/admin.cshtml";
}


@using (Html.BeginForm("rolekle", "admin", FormMethod.Get))
{
    <p>ARANACAK ROL ADI:@Html.TextBox("p")
        <input type="submit" value="ARA"/>
    </p>
    
}
@model IEnumerable<proje.Models.rol>
<table class="table table-bordered">
    <tr>
        <th>ROL ID</th>
        <th>ROL ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        
        
    </tr>
    <tbody>
         @foreach (proje.Models.rol rol in Model)
         {
             <tr>
                 <th>@rol.rol_id</th>
                 <td>@rol.rol_adi</td>
                 <td><a href="/admin/rolsil/@rol.rol_id" class="btn btn-warning">SİL</a></td>
                 <td><a href="/admin/rolguncele/@rol.rol_id" class="btn btn-primary">GÜNCELLE</a></td>
                
             </tr>
         }
    </tbody>
</table>
@*<a href ="yenirol" class="btn btn-danger">YENİ ROL EKLE</a>*@
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Rol Ekle
</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">ROL EKLEME EKRANI</h2>

            </div>
            <form method="post" action="yenirol">
                <div class="modal-body">
                   
                    <br />
            <label>ROLADI</label>
        <input type="text" class="form-control" name="rol_adi" />
                    <br />
        
        <button class="btn btn-danger">ROL EKLE</button>
    </div>
        </form>
        </div>

    </div>
</div>



Views/admin/yazaronaylari.cshtml
@{
    ViewBag.Title = "YAZAR ONAYLARI";
    Layout = "~/Views/Shared/admin.cshtml";
}

@model IEnumerable<proje.Models.kullanici>
<table>
@foreach (proje.Models.kullanici item in Model)
{
    <tr>
            <td> @item.kullaniciadi  </td>
         <td> <a href="/admin/onayver/@item.kullanici_id">ONAY VER </a> </td>
       
    </tr>
}

</table>

Views/admin/yeniadmin.cshtml
@{
    ViewBag.Title = "yeniadmin";
    Layout = "~/Views/Shared/ViewPage2.cshtml";
}

<h2>YENİ ADMİN</h2>
<form  class="form-group" method="post">
    <div>

        <label>ADMİN KULLANICI ADI</label>
        <input type="text" class="form-control" name="admin_ka" />
    </div>
    <div>

        <label>ADMİN ŞİFRE</label>
        <input type="text" class="form-control" name="admin_sf" />
    </div>
    <div>
        <button class="btn btn-danger">ADMİN EKLE</button>
    </div>
</form>


Views/admin/yenietiket.cshtml
@{
    ViewBag.Title = "YENİ KATEGORİ";
    Layout = "~/Views/Shared/ViewPage2.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>ETİKET ADI</label>
        <input  type="text"class="form-control" name="etiked_adi"/>
    </div>
    <div>
        <button class="btn btn-success">ETİKET EKLE</button>
    </div>

</form>

Views/admin/yenirol.cshtml
@{
    ViewBag.Title = "yenirol";
    Layout = "~/Views/Shared/ViewPage2.cshtml";
}

<h2>YENİ ROL</h2>
<form  class="form-group" method="post">
    <div>

        <label>ROL ADI</label>
        <input type="text" class="form-control" name="rol_adi" />
    </div>
    <div>
        <button class="btn btn-danger">ROL EKLE</button>
    </div>
</form>